### ISSUE TITLE
Implement support for other operating systems

### ISSUE THREAD

**Issue by bbenefield89** [bbenefield89/PythonAlarm#5]
### Expected Behavior
Pylarm should work for each of the three major operating systems

### Actual Behavior
Currently only works for
- [x] Linux
- [x] Darwin/MacOS
- [x] Windows

### Steps to Reproduce (if any)
Run Pylarm on a system that is not currently supported

### Proposed Solution (if any)
In `/src/helpers/call_notification.py` find your OS portions `if` block and write out the code to

1. Call your OS notification system
2. Call your OS play-back system call (e.g. Linux: paplay)

**Comment by etisdew** [comment]
See PR #23 
I believe this is what you needed.
